# https://github.com/djezzzl/database_consistency/blob/master/rails-example/.database_consistency.yml
DatabaseConsistencySettings:
  color: true
  log_level: DEBUG

DatabaseConsistencyCheckers:
  MissingIndexChecker:
    enabled: true
  MissingUniqueIndexChecker:
    enabled: true
  ColumnPresenceChecker:
    enabled: true
  NullConstraintChecker:
    enabled: true
  BelongsToPresenceChecker:
    enabled: true

ActiveStorage::Blob:
  enabled: false

ActiveStorage::Attachment:
  enabled: false
