version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Update bundler
          command: gem install bundler
      - ruby/bundle-install
      - run:
          name: Run lints
          command: bin/lint
      

