default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/0") %>

development:
  <<: *default
  channel_prefix: rubyists_development

test:
  adapter: async

production:
  <<: *default
  channel_prefix: rubyists_production
